### ISSUE TITLE
Wacky uPnP implementation on old routers 

### ISSUE THREAD

**Issue by Amphaal** [Amphaal/rpgrpz#53]
Since most home routers may start to enforce uPnP IPv6 process to negociate port opening, we need to handle that.

I need an IPv6-enabled router to test that tho.

**Comment by gg-vara** [comment]
Some ISP routers handle IGDv2 with FirewallControl, but may not allow TCP port forwarding ! Since UDP hole punching is mandatory on every implementation of uPnP, we might need to use something not TCP-related for our network capabilities, QUIC being the first in mind.

I also stumbled accross wacky IGDv2 implementations from SFR devices, which is oddly specific and tiresome...

**Comment by gg-vara** [comment]
No issues so far with Free routing device regarding uPnP implementation... Let's keep our eyes open on this issue, but closing this ticket for now.
